### PR TITLE
tighten up deployment

### PR DESCRIPTION
**Pull request by whit537**
- symlink nginx.conf for direct use
 - symlink post-receive for direct use
 - update README

### CODE REVIEW

**Comment by whit537** [comment]
Ping @techtonik, redux of #114.

**Comment by whit537** [comment]
Rebased to squash tiny commits. Previous head was ca099efdd255cf4d4bdbe3e0d5e4ad67a8d9c99d.

**Comment by whit537** [comment]
I've turned on branch protection for master and have set up the symlinks in production.

screen shot 2016-02-16 at 8 51 20 am

**Comment by techtonik** [comment]
:+1: !m @whit537

**Pull request merged**
