### PR TITLE
store nginx conf in the repo

### PR DESCRIPTION
**Pull request by whit537**
Better for change management.

### CODE REVIEW

**Comment by whit537** [comment]
cc: @techtonik @mattbk

**Comment by whit537** [comment]
After merging and deploying we should update production to symlink the conf file here.

**Comment by techtonik** [comment]
Actually there is nginx.conf already in https://github.com/gratipay/grtp.co/tree/master/infra - not sure if it is actual.

**Comment by whit537** [comment]
@techtonik Ah, nice! Looks like they're the same (except for an errant newline in this PR's version):

https://raw.githubusercontent.com/gratipay/grtp.co/6bdb5849e8311faacf858eb688e1090bc205b37d/grtp.co-nginx

https://raw.githubusercontent.com/gratipay/grtp.co/e41d094ad27d56573e80e4372408344c9b128e75/infra/nginx.conf

**Pull request closed without merging**
