### PR TITLE
Hard-code the production path

### PR DESCRIPTION
**Pull request by whit537**
Works around errors such as #142.

### CODE REVIEW

**Comment by whit537** [comment]
Reopened to bump Travis.

**Comment by whit537** [comment]
Alright, looks like GitHub is back to normal. You good with this PR, @nashe?

**Comment by nashe** [comment]
LGFM, anyway we'll quickly know if it breaks again ;-)

**Comment by whit537** [comment]
@nashe May I give you the honor of merging this PR? Our general policy is not to merge our own PRs, if we can help it. :)

**Comment by whit537** [comment]
Huzzah! Don't forget to delete the branch as well. :-)

**Pull request merged**
