### PR TITLE
Tweak Travis

### PR DESCRIPTION
**Pull request by whit537**
- Only one build per-PR
 - turn off IRC notifications

cf. https://github.com/gratipay/postgres.py/pull/57

### CODE REVIEW

**Comment by whit537** [comment]
cc: @techtonik et al.

**Comment by techtonik** [comment]
Ok for disabling IRC, but why don't build branches?

**Comment by whit537** [comment]
> why don't build branches?

Because then we end up with two Travis builds per pull request, because of the way GitHub does pull requests. If I understand it right, GitHub automatically makes a merge commit for each pull request (I presume this is how they can determine whether the branch merges cleanly or not). Since the `master` branch is involved in the merge commit, by constraining to just `master` on Travis, we still get a test run for each commit on each pull request commit.

See #3187 for where we introduced this on `gratipay.com`.

**Comment by techtonik** [comment]
> Because then we end up with two Travis builds per pull request, because of the way GitHub does pull requests. 

I look through Travis and can't see where PR commits are built on branches. Can you show an example of these two builds?

**Comment by whit537** [comment]
@techtonik Notice the two checks on #116, e.g., while there's only one check here.

screen shot 2016-02-16 at 8 33 32 am

screen shot 2016-02-16 at 8 33 40 am

**Comment by whit537** [comment]
See also: https://github.com/travis-ci/travis-ci/issues/3241.

**Comment by whit537** [comment]
> Rather than test the commits from the branches the pull request is sent from, we test the merge between the origin and the upstream branch.

https://docs.travis-ci.com/user/pull-requests

That makes it sound like if you test on all branches *and* you test pull requests, then you get two builds per PR (one for the branch, one for the PR merge commit) ... but if you only test the `master` branch *and* you test pull requests, then you get builds for each master commit and a build for each PR merge commit.

**Comment by techtonik** [comment]
Now I see.

**Comment by techtonik** [comment]
Looks like Travis couldn't understand this request and hung.

**Comment by techtonik** [comment]
Rebased.

**Comment by techtonik** [comment]
And merged!

**Comment by whit537** [comment]
Yay! :dancer: 

P.S. @techtonik When you rebase can you leave the commit hash of the previous head in a comment for future reference? Thanks. :-)

**Comment by techtonik** [comment]
> leave the commit hash of the previous head in a comment

But when I force push it, it is gone, no?

**Comment by whit537** [comment]
@techtonik It's not listed on this PR anymore, but GitHub still keeps it around so we can browse it if we want to.

**Comment by techtonik** [comment]
Ok. I'll keep this in mind.

**Pull request merged**
