### PR TITLE
Fix amount formatting

### LINKED ISSUE #110: Fix trailing zeros in team receiving widget
Reticketed from https://github.com/gratipay/grtp.co/issues/103#issuecomment-166898549.

> I get the following Team widget though (https://gratipay.com/northern-plains-athletics/public.json), need to fill in trailing zeros:
image

### PR DESCRIPTION
**Pull request by whit537**
Fixes #110 and #140.

screen shot 2016-07-14 at 7 23 46 pm

### CODE REVIEW

**Comment by mattbk** [comment]
Ahh, that's where that pesky $ was.

**Comment by whit537** [comment]
Yeah, it was a little tricky because we have a dollar sign in the `<b></b>` in the HTML, but that gets overwritten by the JavaScript.

**Comment by whit537** [comment]
Deploying ...

**Comment by whit537** [comment]
Deployed! :-)

**Comment by mattbk** [comment]
Works!
image

**Pull request merged**
