### PR TITLE
Rip out v1 goals.

### LINKED ISSUE #122: Remove goal progress from custom widgets
Unless there are actual goals, this doesn't need to be in the code anymore.

### PR DESCRIPTION
**Pull request by mattbk**
Redo of #125, closes #122.

### CODE REVIEW

**Comment by mattbk** [comment]
Goals were killed on the gratipay.com side in https://github.com/gratipay/gratipay.com/pull/3405.

Ready for review, @techtonik.

**Comment by techtonik** [comment]
It is a pity that personal goals (which I read as TCYLO - total cost of your life ownership) are ripped, but we may take them back if TCYLO metrics/stats idea will get traction one day. Let me some hours to setup dev environment, because https://glitch.com/edit/#!/grtp-co fails to bootstrap grtp.co

**Comment by techtonik** [comment]
Okay. We need API CHANGELOG to record these changes, because it may break people scripts and people need a quick way to discover what happens and fix them. For example, if they parse JSON into an object of their own and expected all current fields like `goal` to be present.

Also, can we get stats about how many widgets are using `goal` field right and if we can reach out to them?

**Comment by techtonik** [comment]
LGTM. There is `goal` field in Graipay API https://gratipay.com/~techtonik/public.json so this widget functionality is essentially broken.

**Comment by techtonik** [comment]
!m @mattbk

**Comment by mattbk** [comment]
> There is goal field in Gratipay API https://gratipay.com/~techtonik/public.json so this widget functionality is essentially broken.

Not anymore.

**Comment by techtonik** [comment]
I often miss words like `no` for some reason and this inverts the meaning.

**Comment by mattbk** [comment]
Oh, I gotcha. :D

**Pull request merged**
