### PR TITLE
Switching to Gulp

### PR DESCRIPTION
**Pull request by techtonik**
I propose a gradual transition from Grunt to Gulp, so that we can have a history of two build systems running in parallel and compare them.

### CODE REVIEW

**Comment by clone1018** [comment]
I'm totally in favor of gulp +1

**Comment by techtonik** [comment]
@clone1018 it can be merged already then. The next step will be to just gradually improve linter and move build stuff from Grunt. I just don't want to mix too much into single PR.

**Comment by whit537** [comment]
How did this never get merged? Rebasing ...

**Comment by whit537** [comment]
Rebased on master at e1c8689. Old head was e8b8aee84c75f0c538df25da5e21c03d6cdf9595.

**Comment by whit537** [comment]
The build is green, though upon inspection, linting fails with 33 errors. We should:

 - update the build to fail on linting errors
 - fix the linting errors :)

**Comment by whit537** [comment]
@techtonik Wanna pick up with this?

**Comment by webmaven** [comment]
@whit537, is @techtonik no longer an active contributor?

**Comment by whit537** [comment]
Seems that way. Happy to have @techtonik or someone else pick up with this PR.

**Comment by webmaven** [comment]
I'll tentatively volunteer.

I can't commit to a time frame yet (I am easing back into things slowly), so if someone else steps forward before I get to this I won't mind.

**Comment by techtonik** [comment]
Because of DalekJS, I can not update grunt and its dependencies, so I resurrected the branch to switch to gulp dependencies, but then I realized that the problem is in DalekJS. It is not updated anymore, and while its syntax is great, we need to switch to alternative.

**Pull request closed without merging**
