### PR TITLE
Check I vs We

### PR DESCRIPTION
**Pull request by mattbk**
Easier than I thought. Closes https://github.com/gratipay/grtp.co/issues/119.

### CODE REVIEW

**Comment by whit537** [comment]
@mattbk Are the new test files actually used in a test?

**Comment by mattbk** [comment]
I got a little mixed up; if they are used in tests, they are related to https://github.com/gratipay/grtp.co/pull/112.

**Comment by mattbk** [comment]
I can fix this one before it gets merged.

**Comment by mattbk** [comment]
Self merging... :ship:

**Pull request merged**
