### PR TITLE
Replace minify task with deploy that also copies Blogger widget files

### PR DESCRIPTION
**Pull request by techtonik**
Ready for review. Ping @rummik =)

### CODE REVIEW

**Comment by techtonik** [comment]
Ping again.

**Comment by techtonik** [comment]
You can test it at https://codenvy.com/ws/techtonik/grtp.co

**Comment by rummik** [comment]
I feel like it should be called `build` rather than `deploy`

**Comment by techtonik** [comment]
Well, copying files to www/ looks like deployment to me. Anyway, if we about to switch to Gulp, we can name it differently from the start there.

**Comment by rummik** [comment]
I usually separate by deploy being deployment to a server, building being compiled/minified, and install being copying it to a system-wide location rather than a local build.  It's also more consistent with the Grunt and Gulp naming for tasks (which often includes minify as a task separate to build)

**Comment by techtonik** [comment]
And I thought that scripting languages are easier than C/C++.. Let me fix that in a minute. )

**Comment by techtonik** [comment]
@rummik, done!

**Comment by techtonik** [comment]
@rummik ?

**Comment by techtonik** [comment]
Ping.

**Comment by techtonik** [comment]
Anybody? @rummik @whit537 @rohitpaulk

**Comment by whit537** [comment]
Doesn't look actively dangerous to me and @rummik [appears](https://gratipay.com/Gratipay/members/) to be away on other business. Merging! :-)

**Comment by techtonik** [comment]
!m @whit537  Thanks. =) Now somebody needs to run deployment in #83.

**Pull request merged**
